### PR TITLE
Feature/initial configs

### PR DESCRIPTION
**Pull request by dulcetti**
#19 

Add initial config to:

- Babel
- ESLint
- CSScomb
- editorconfig
- postcss
- Package.json

## Next features
- Add Webpack
- Change tests of Karma to Jest

### CODE REVIEW

**Comment by alvaromontoro** [comment]
That's a lot of changes. Let me review before I approve the merge.

**Comment by dulcetti** [comment]
No problem. The tests don't work yet. I will resolve.

**Comment by dulcetti** [comment]
I putted one configuration of eslint. Review and if you can, change it or tell me ;)

**Comment by alvaromontoro** [comment]
@dulcetti  This is a ton of code to review. Some of the changes seem unnecessary (csscomb, editorconfig); and some other are nice, but seem unrelated and maybe would be better in a different ticket/PR (lint, testing). I will look into it during the weekend.

**Comment by dulcetti** [comment]
@alvaromontoro Well, I thinkthe editorconfig important, but ok.

Yeah, about tests I will create a Issue. You prefer create one PR for each setting? (lint, etc)

**Pull request merged**
